<?php

namespace Database\Factories;

use App\Models\Tourguide;
use App\Models\Tourist;
use App\Models\Order;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Order>
 */
class OrderFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    protected $model = Order::class;
    public function definition(): array
    {
        $cities = [
            "Cairo",
            "Giza",
            "Luxor",
            "Aswan",
            "Alexandria",
            "Sharm El Sheikh",
            "Hurghada",
            "Dahab",
            "Siwa Oasis",
            "Marsa Alam",
            "Abu Simbel",
            "El Minya",
            "Ismailia",
            "Port Said",
            "Taba",
        ];
        $notes = [
            "Can we take a detour to explore that charming market?",
            "What's the best local dish you recommend trying?",
            "Could you share some interesting facts about this historical site?",
            "Is there a good spot around here for souvenir shopping?",
            "Any recommendations for a scenic photo spot?",
            "Can we have a brief overview of the day's itinerary?",
            "Is there a restroom nearby?",
            "I'd love to learn a few phrases in the local language, can you teach me?",
            "Do you have any tips for capturing great wildlife photos?",
            "Could you suggest a nice place for a coffee break?",
            "What's the weather forecast for the afternoon?",
            "Can we visit a traditional artisan's workshop?",
            "Any famous personalities associated with this location?",
            "Are there any upcoming local events or festivals?",
            "Can you recommend a good hiking trail in the area?",
            "Could you provide some insight into the local customs and traditions?",
            "Is there a good vantage point for a panoramic view of the city?",
            "Can you recommend a family-friendly activity for the afternoon?",
            "Any local legends or folklore related to this place?",
            "What's the best way to travel between these two attractions?",
            "Could you suggest a restaurant with authentic regional cuisine?",
            "Is there a local market open today, and what's it known for?",
            "Can you share some safety tips for exploring this area?",
            "Any interesting wildlife we might encounter on our journey?",
            "What's the significance of the architecture in this part of the city?",
            "Can you recommend a good spot to catch the sunset?",
            "Are there any restrictions or rules we should be aware of?",
            "Could you suggest a good place to experience the local nightlife?",
            "Is there a specific time when this place is less crowded?",
            "Any off-the-beaten-path gems you'd recommend exploring?",
            "Can you tell us about the history behind this famous landmark?",
            "What's the best mode of transportation for getting around the city?",
            "Any local superstitions or beliefs we should be aware of?",
            "Can you recommend a family-friendly museum in the area?",
            "Are there any traditional music performances happening today?",
            "Could you provide some insights into the local art scene?",
            "Is there a good place to rent bicycles for a leisurely ride?",
            "Can you share some insider tips for navigating the public transport system?",
            "What's the best time to visit the botanical gardens?",
            "Could you recommend a good bookstore or library nearby?",
            "Any famous movies filmed in or inspired by this location?",
            "Can you suggest a good location for bird watching?",
            "Is there a local specialty food that we must try?",
            "Any haunted or spooky places in the vicinity?",
            "Can you recommend a good place for stargazing?",
            "What's the best way to learn about the local arts and crafts?",
            "Are there any restrictions on photography in this area?",
            "Can you share some tips for bargaining at the local markets?",
            "Is there a good spot for a picnic in the nearby park?",
            "Could you recommend a good historical fiction book set in this region?",
            "What's the most Instagram-worthy spot around here?",
            "Can you suggest a good place to learn traditional dance?",
            "Are there any volunteer opportunities for tourists in this area?",
            "Could you recommend a good spa for some relaxation?",
            "Is there a local dish that's considered a hidden gem?",
            "Can you provide information about public art installations in the city?",
            "What's the best way to experience the local music scene?",
            "Are there any local environmental conservation initiatives we can support?",
            "Can you recommend a good place for a morning jog?",
            "Is there a specific dress code for entering religious sites?",
            "Any unique customs related to greetings we should be aware of?",
            "Can you recommend a good spot for watching the sunrise?",
            "What's the best way to engage with the local community here?",
            "Are there any eco-friendly initiatives happening in the area?",
            "Can you suggest a good spot for a romantic evening?",
            "Any recommendations for vegetarian-friendly restaurants?",
            "Is there a place where we can learn about traditional medicine?",
            "What's the best way to get involved in local cultural events?",
            "Can you recommend a good location for a photography workshop?",
            "Are there any art galleries showcasing local artists?",
            "Can you provide information about the local flora and fauna?",
            "What's the best way to explore the city's street art scene?",
            "Are there any local crafts workshops we can participate in?",
            "Can you recommend a good place to try street food?",
            "Is there a local dish that's known for its unique preparation?",
            "What's the best way to learn about the indigenous communities here?",
            "Can you suggest a good place to experience traditional music performances?",
            "Any recommendations for a family-friendly adventure activity?",
            "Is there a good location for a nature walk in the vicinity?",
            "Can you share some insights into the local fishing traditions?",
            "What's the best way to immerse ourselves in the local lifestyle?",
            "Are there any cultural events or festivals happening during our visit?",
            "Can you recommend a good spot for a photography exhibition?",
            "Is there a place where we can learn about local farming practices?",
            "Any famous literature or books inspired by this region?",
            "Can you suggest a good location for a historical reenactment?",
            "What's the best way to experience the local culinary scene?",
            "Are there any wildlife conservation projects we can support?",
            "Can you recommend a good place for a family picnic?",
            "Is there a specific area known for its vibrant street markets?",
            "Any recommendations for a scenic boat ride in the area?",
            "Can you share some tips for sustainable travel in this region?",
            "What's the best way to explore the city's architectural heritage?",
            "Are there any guided tours focusing on local folklore and myths?",
            "Can you suggest a good location for a cultural exchange program?",
            "Is there a specific spot where we can learn about local astronomy?",
            "What's the best way to support local artisans and craftsmen?",
            "Can you recommend a good place for a wildlife photography workshop?",
            "Any recommendations for a family-friendly science museum?",
            "Is there a local dish that's considered a culinary masterpiece?"
        ];
        $phone = [
            '+12056543278',
            '+12058927431',
            '+12051234567',
            '+120599876543',
            '+12058765432',
            '+12055432789',
            '+12054567890',
            '+12051357924',
            '+12052468013',
            '+12057777777',
            '+12058888888',
            '+12059999999',
            '+12057654321',
            '+12052345678',
            '+12051111111',
            '+12052222222',
            '+12053333333',
            '+12054444444',
            '+12055555555',
            '+12056666666',
            '+12057771234',
            '+12058901234',
            '+12054321789',
            '+12055432198',
            '+12057890123',
            '+12056547890',
            '+12058907654',
            '+12051230987',
            '+12057896543',
            '+12058760123',
        ];
        $tourguideId = Tourguide::inRandomOrder()->first()->id;
        $touristId = Tourist::inRandomOrder()->first()->id;
        return [
            'tourist_id'=> $touristId,
            'tourguide_id'=> $tourguideId,
            'comment'=>$this->faker->randomElement($notes),
            'phone'=>$this->faker->randomElement($phone),
            'from'=>$this->faker->dateTimeBetween('now','+5 days'),
            'to'=>$this->faker->dateTimeBetween('+5 days','+10 days'),
            'total'=>$this->faker->numberBetween(900,200),
            'city'=>  $this->faker->randomElement($cities),
            'status'=>$this->faker->randomElement(['pending', 'rejected', 'accepted']),
        ];
    }
}
