version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - production

jobs:
  build:
    docker:
      - image: cimg/base:2023.01

    steps:
      - checkout

      # Install lftp
      - run:
          name: Install lftp
          command: sudo apt-get update && sudo apt-get install lftp -y

      # Execute the deployment script for the production branch
      - run:
          name: Deploy to cPanel for production branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              bash .circleci/deploy.sh
            else
              echo "Skipping deployment for branch ${CIRCLE_BRANCH}"
            fi
