version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - production

jobs:
  build:
    docker:
      - image: circleci/php:7.4

    steps:
      - checkout

      # Update Composer Dependencies
      - run:
          name: Update Composer Dependencies
          command: composer update --no-scripts

      # Install your project dependencies
      - run:
          name: Install Composer Dependencies
          command: composer install --no-scripts

      # Install Node.js and npm
      - run:
          name: Install Node.js and npm
          command: |
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            npm install

      # Install lftp
      - run:
          name: Install lftp
          command: sudo apt-get update && sudo apt-get install lftp -y

      # Clear Composer Cache
      - run:
          name: Clear Composer Cache
          command: composer clear-cache

      # Execute the deployment script for the production branch
      - run:
          name: Deploy to cPanel for production branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              bash .circleci/deploy.sh
            else
              echo "Skipping deployment for branch ${CIRCLE_BRANCH}"
            fi
